### ISSUE TITLE
Request - High contrast border between terminals

### ISSUE THREAD

**Issue by ghost** [roydukkey/chimera-theme#3]
Howdy,

I wanted to request a more visible border between terminals in a similar to the Dracula theme (example attached). I find that with 2+ terminals open, it can be difficult to tell where one ends and another starts.

I can easily set a brighter color in my local settings but thought it might be worth making the suggestion. Either way, thank you for sharing such a nice theme, I'm hooked.

![image](https://user-images.githubusercontent.com/7434573/69784231-3c0f6600-1205-11ea-864c-b4e19acb8984.png)

**Comment by roydukkey** [comment]
Thank you for using this theme. I'm glad to hear others find it useful. And, thank you for submitting this request.

I have created this theme specifically because I didn't like how loud (bright) the Dracula theme was. I also thought that the syntax highlighting was incomplete, and thus decided to start from the vsCode Dark/+ themes. I have work very hard to bring a logic to the order in which the colours are applied to different structures, attempting to have the loudest colours appear more infrequently.

Therefore, the feature of Dracula which you have mentioned is one that I have specifically decided not to include in this theme.

Thanks again for using this theme. There are other area of the theme I feel are in need of some tweaking, but I haven't had the time to do so. Please feel free to open other issues.
